spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    username: user
    password: password
    url: jdbc:mysql://database:3306/lessons?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC